### ISSUE TITLE
Pisanje dokumentacije

### ISSUE THREAD

**Issue by NikolaJelic** [OSI2021-Grupa-1/softver-za-prodavnice#20]
Potrebno je napisati dokumentaciju za sve metode i klase u programu.
Ovo se moze raditi tek kada se omoguci rad alata [Doxygen](https://www.doxygen.nl/index.html) #19 
Dokumentacija se dodaje pisanjem komentara odredjenog formata iznad svake funkcije

**Comment by djmaki01** [comment]
Dokumentacija napisana bez upotrebe _Doxygen_-a.
